
# single machine
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.85
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true


# cluster
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer5:8762/eureka,http://peer6:8766/eureka
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    prefer-ip-address: true
#    hostname: peer1
#    lease-renewal-interval-in-seconds: 5

# cluster final
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka,http://peer5:8765/eureka,http://peer6:8766/eureka
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    prefer-ip-address: true
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 5